export const  ADD_ROW:string = 'ADD_ROW'
export const DELETE_ROW:string = 'DELETE_ROW'
export const INCREASE_AMOUNT:string = 'INCREASE_AMOUNT'
export const  MOUSE_OVER_CEIL:string = 'MOUSE_OVER_CEIL'
export const  MOUSE_OVER_SUM:string = 'MOUSE_OVER_SUM'
export const  MOUSE_OUT:string = 'MOUSE_OUT'
