export const  ADD_ROW = 'ADD_ROW'
export const DELETE_ROW = 'DELETE_ROW'
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT'
export const  MOUSE_OVER_CEIL = 'MOUSE_OVER_CEIL'
export const  MOUSE_OVER_SUM = 'MOUSE_OVER_SUM'
export const  MOUSE_OUT = 'MOUSE_OUT'
